spring:
    application:
        name:config-server
    cloud:
        config:
            server:
                git:
                    uri:https://github.com/yusufkaan345/java-4.5
                    default-label:main
                    search-paths: 
                        - configurations/
                        - configurations/{application}

server:
    port: 8787